title: TheFlex Industry Browser
description: The Android and iOS browser for production, logistics ans SAP
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
